[package]
name = "today"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
codespan-reporting = "0.11.1"
colored = "2.0.0"
computus = "1.0.0"
directories = "4.0.1"
edit = "0.1.3"
pest = "2.1.3"
pest_derive = "2.1.0"
structopt = "0.3.25"
termcolor = "1.1.2"
thiserror = "1.0.30"
tzfile = { git = "https://github.com/Garmelon/tzfile.git", branch = "tzdir" }
