[package]
name = "today"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4.19"
computus = "1.0.0"
directories = "4.0.1"
pest = "2.1.3"
pest_derive = "2.1.0"
structopt = "0.3.25"
thiserror = "1.0.30"
tzfile = "0.1.3"
